[workspace]
resolver = "3"
members = ["core", "cli", "engine"]

[workspace.dependencies]
anyhow = "1.0"
autonomi = "0.4.5"
bytes = "1.10"
chrono = "0.4"
futures = "0.3"
futures-util = "0.3"
tokio = "1.44"
tracing = "0.1"
url = "2.5"
zeroize = "1.8"
